piVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker
  labels:
        app: myappbroker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myappbroker
  template:
    metadata:
      labels:
        app: myappbroker
    spec:
#      dnsPolicy: ClusterFirstWithHostNet
#      hostNetwork: true
      containers:
      - name: broker-container
        image: hivemq/hivemq-ce
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "0.6Gi"
            cpu: "300m"
          requests:
            memory: "0.2Gi"
            cpu: "150m"
        ports:
        - containerPort: 1883



