apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
spec:
  selector:
    app: myappbroker
#  type: LoadBalancer
  type: NodePort
  ports:
  - port: 1883
    targetPort: 1883
    nodePort: 30005
